export const tunisiaCities = [
    "Tunis",
    "Sfax",
    "Sousse",
    "Ettadhamen",
    "Kairouan",
    "Gabes",
    "Bizerte",
    "Ariana",
    "Gafsa",
    "El Mourouj",
    "Tataouine",
    "Kasserine",
    "Kairouan",
    "Medenine",
    "Monastir",
    "La Goulette",
    "Sidi Bouzid",
    "Ben Arous",
    "Tozeur",
    "Nabeul",
    "Zarzis",
    "Beni Khiar",
    "Hammamet",
    "Metlaoui",
  ];
  export const categories = [
    "Cleaning",
    "Lawn & Garden",
    "Handyman",
    "Home Automation",
    "Organization",
    "Moving & Storage",
    "Renovation",
    "Pest Control",
    "Other",
  ];